[package]
name = "rust_game"
version = "0.1.0"
edition = "2021"

[dependencies]
cgmath = "0.18.0"
gltf = "1.4.1"
image = "0.25.5"
vulkano = "0.34.0"
vulkano-shaders = "0.34.0"
winit = "0.28"

[profile.dev.package."*"]
opt-level = 3